### ISSUE TITLE
It needs to be inside a sketch folder named "PianoVisualizer"

### ISSUE THREAD

**Issue by ChrisTorng** [wiwikuan/PianoVisualizer#1]
I cloned this repo. While opening PianoVisualizer.pde, the Processing 3 shows:

> The file "PianoVisualizer.pde" needs to be inside a sketch folder named "PianoVisualizer".
> Create this folder, move the file, and continue?

If press OK, then the file will be moved under folder "PianoVisualizer". I wish to contribute to this repo. This problem makes contribution harder. (Will you accept Pull Request?)

I suggest to rename this repo to "PianoVisualizer" to avoid this extra moving. Or create "PianoVisualizer" folder under this repo.

**Comment by wiwikuan** [comment]
OK, I renamed the repo. Thanks for the suggestion!
