### ISSUE TITLE
Support languages policy

### ISSUE THREAD

**Issue by ChrisTorng** [wiwikuan/PianoVisualizer#2]
What policy of display languages do you prefer? All English? Or English, Traditional Chinese with Simplified Chinese? Where? In code? Config? Readme? Issues?

I suggest to use English in code and config, with readme in three languages. Issues opens to anyone with any languages they prefer.

No matter which policy you prefer, I can help with English, Traditional Chinese, and translated Simplified Chinese version.

**Comment by wiwikuan** [comment]
"English in code and config, with readme in three languages" is good!
